PokeTradR/force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Individual Offers made by users per Trade</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/objects/Offer__c/fields/Accepted__c.field-meta.xml
<CustomField>
    <fullName>Accepted__c</fullName>
    <description>Whether the offer has been accepted</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PokeTradR/force-app/main/default/objects/Offer__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Offers (Recipient)</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Offer__c/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <label>Trade</label>
    <referenceTo>Trade__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

PokeTradR/force-app/main/default/objects/Offer__c/fields/Trainer_Name__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Name__c</fullName>
    <label>Trainer Name</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <description>Trade post made by users</description>
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/objects/Trade__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Trades (Recipient)</relationshipLabel>
    <relationshipName>Trades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trade__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status on the Trade</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PokeTradR/force-app/main/default/objects/Trade__c/fields/Trainer_Name__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Name__c</fullName>
    <label>Trainer Name</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Trades</relationshipLabel>
    <relationshipName>Trades1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <description>Account of Trainers</description>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Active - Profile can make trades and offers
Inactive - Profile can&apos;t make trades and offers
Frozen - Profile temporarily cannot make trades</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PokeTradR/force-app/main/default/classes/TradeTest.cls
@isTest
public class TradeTest {
	
    @isTest static void testTradeExtension() {
        PageReference testPage = Page.TradeSelectionPage;
        Trainer__c test1 = new Trainer__c (
            Name='Test1'
        );
        Trainer__c test2 = new Trainer__c (
            Name='Test2'
        );
        insert test1;
        insert test2;
        List<Trainer__c> tList = [
            SELECT Id, Name
            FROM Trainer__c
            WHERE Name Like '%Test%'
        ];
        
        Trade__c testTrade = new Trade__c(
            Name='TestTrade',
            Trainer_Name__c=tList[0].Id,
            Recipient__c=tList[1].Id,
            Status__c='New'
        );
        
        insert testTrade;
        
        Offer__c testOffer = new Offer__c(
        	Name='TestOffer',
            Owner__c=tList[0].Id,
            Trainer_Name__c=tList[1].Id,
            Trade__c=testTrade.Id,
            Accepted__c='Accepted'
        );
        Offer__c testOffer2 = new Offer__c(
        	Name='TestOffer2',
            Owner__c=tList[0].Id,
            Trainer_Name__c=tList[1].Id,
            Trade__c=testTrade.Id,
            Accepted__c='Pending'
        );
        
        insert testOffer;
        insert testOffer2;
        Test.startTest();
        Test.setCurrentPage(testPage);
        TradeExtension ext = new TradeExtension(new ApexPages.StandardController(testTrade));
        TradeExtension.currentId = [
            SELECT Id
            FROM Trade__c
            WHERE Name='TestTrade'
            LIMIT 1
        ].Id;
        
        PageReference pr = Page.TradePage;
        pr.getParameters().put('id', TradeExtension.currentId);

        ext.saveOfferChanges();
        Test.stopTest();
        System.assertEquals(TradeExtension.currentId, testTrade.Id);
        System.assertEquals(ext.goToTrade().getUrl(), pr.getUrl());
        System.assertEquals(True, ext.offers.size()>0);
        System.assertEquals('TestOffer', ext.currOffer.Name);
        System.assertEquals(True, ext.recipientTrainer != null);
        System.assertEquals(True, ext.getRecBio() != null);
        System.assertEquals(True, ext.getRecName() != null);
        System.assertEquals(True, ext.getRecRank() != null);
        System.assertEquals('Declined', ext.offers[1].Accepted__c);
    }
    
    @isTest static void testNegative() {
        Trainer__c tester4 = new Trainer__c (
            Name='Tester3'
        );
        Trainer__c tester3 = new Trainer__c (
            Name='Tester4'
        );
        insert tester3;
        insert tester4;
        List<Trainer__c> tList2 = [
            SELECT Id, Name
            FROM Trainer__c
            WHERE Name Like '%Tester%'
        ];
        Trade__c testTrade2 = new Trade__c(
            Name='TestTrade2',
            Trainer_Name__c=tList2[0].Id,
            Recipient__c=tList2[1].Id,
            Status__c='New'
        );
        
        Test.startTest();
        TradeExtension ext2 = new TradeExtension(new ApexPages.StandardController(testTrade2));
        PageReference pr2 = Page.TradePage;
        Test.stopTest();
        System.assertEquals(False, ext2.offers.size()>0);
        System.assertEquals(null, ext2.currOffer.Name);
        System.assertEquals(True, ext2.recipientTrainer == null);
        System.assertEquals(False, ext2.getRecBio() != null);
        System.assertEquals(False, ext2.getRecName() != null);
        System.assertEquals(False, ext2.getRecRank() != null);
    }
}