PokeTradR/force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <description>Individual Offers made by users per Trade</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/objects/Offer__c/fields/Accepted__c.field-meta.xml
<CustomField>
    <fullName>Accepted__c</fullName>
    <description>Whether the offer has been accepted</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PokeTradR/force-app/main/default/objects/Offer__c/fields/Money_Offered__c.field-meta.xml
<CustomField>
    <fullName>Money_Offered__c</fullName>
    <description>How much money is offered by a trainer</description>
    <label>Money Offered</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Offer__c/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <label>Trade</label>
    <referenceTo>Trade__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

PokeTradR/force-app/main/default/objects/Offer__c/fields/Trainer_Name__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Name__c</fullName>
    <label>Trainer Name</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokedex Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemon</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/objects/Pokemon__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <label>Pokemon</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pokemon</valueSetName>
    </valueSet>
</CustomField>

PokeTradR/force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <description>Trade post made by users</description>
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/objects/Trade__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pokemon</label>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Trades (Pokemon)</relationshipLabel>
    <relationshipName>Trades</relationshipName>
    <type>Lookup</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trade__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Trades (Recipient)</relationshipLabel>
    <relationshipName>Trades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trade__c/fields/Trainer_Name__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Name__c</fullName>
    <label>Trainer Name</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Trades</relationshipLabel>
    <relationshipName>Trades1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <description>Account of Trainers</description>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Bio__c.field-meta.xml
<CustomField>
    <fullName>Bio__c</fullName>
    <label>Bio</label>
    <type>TextArea</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <description>Based on total of Trades Made and Offers Made it will cause the Trainer Rank to assign: 
Rookie (&lt;25), 
Intermediate(&gt;= 25 &amp; &lt;50),
Advanced (&gt;= 50 &amp; &lt;75)
Master(&gt;= 75 &amp; &lt;100)</description>
    <label>Rank</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Trainer_ID__c.field-meta.xml
<CustomField>
    <fullName>Trainer_ID__c</fullName>
    <displayFormat>{0000}</displayFormat>
    <label>Trainer ID</label>
    <type>AutoNumber</type>
</CustomField>

PokeTradR/force-app/main/default/globalValueSets/Pokemon.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abra</fullName>
    </customValue>
    <customValue>
        <fullName>Aerodactyl</fullName>
    </customValue>
    <customValue>
        <fullName>Alakazam</fullName>
    </customValue>
    <customValue>
        <fullName>Arbok</fullName>
    </customValue>
    <customValue>
        <fullName>Arcanine</fullName>
    </customValue>
    <customValue>
        <fullName>Articuno</fullName>
    </customValue>
    <customValue>
        <fullName>Beedrill</fullName>
    </customValue>
    <customValue>
        <fullName>Bellsprout</fullName>
    </customValue>
    <customValue>
        <fullName>Blastoise</fullName>
    </customValue>
    <customValue>
        <fullName>Bulbasaur</fullName>
    </customValue>
    <customValue>
        <fullName>Butterfree</fullName>
    </customValue>
    <customValue>
        <fullName>Caterpie</fullName>
    </customValue>
    <customValue>
        <fullName>Chansey</fullName>
    </customValue>
    <customValue>
        <fullName>Charizard</fullName>
    </customValue>
    <customValue>
        <fullName>Charmander</fullName>
    </customValue>
    <customValue>
        <fullName>Charmeleon</fullName>
    </customValue>
    <customValue>
        <fullName>Clefable</fullName>
    </customValue>
    <customValue>
        <fullName>Clefairy</fullName>
    </customValue>
    <customValue>
        <fullName>Cloyster</fullName>
    </customValue>
    <customValue>
        <fullName>Cubone</fullName>
    </customValue>
    <customValue>
        <fullName>Dewgong</fullName>
    </customValue>
    <customValue>
        <fullName>Diglett</fullName>
    </customValue>
    <customValue>
        <fullName>Ditto</fullName>
    </customValue>
    <customValue>
        <fullName>Dodrio</fullName>
    </customValue>
    <customValue>
        <fullName>Doduo</fullName>
    </customValue>
    <customValue>
        <fullName>Dragonair</fullName>
    </customValue>
    <customValue>
        <fullName>Dragonite</fullName>
    </customValue>
    <customValue>
        <fullName>Dratini</fullName>
    </customValue>
    <customValue>
        <fullName>Drowzee</fullName>
    </customValue>
    <customValue>
        <fullName>Dugtrio</fullName>
    </customValue>
    <masterLabel>Pokemon</masterLabel>
</GlobalValueSet>

PokeTradR/force-app/main/default/classes/TradeController.cls
public class TradeController {

   //Variables
    
    public Trade__c currTrade;
    public Offer__c currOffer;   
    public List<Offer__c> offers {get {
        if (this.offers == null) {
            this.offers = [
                SELECT Name, Accepted__c, Pokemon__c, Money_Offered__c, Trainer_Name__c
                FROM Offer__c
                WHERE Trade__r.Id=:currTrade.Id
            ];
        }
        return this.offers;
    }set;} 

    public  List<Trainer__c> recipientTrainer {get {
        if (this.currTrade != null) {
            this.recipientTrainer = [
                SELECT Name, Id, Trainer_Id__c, Bio__c, Rank__c 
                FROM Trainer__c 
                WHERE Id =:currTrade.Recipient__c
            ];
        }
        return this.recipientTrainer;
    }set;}
    
    public Component.Apex.OutputText getRec(){
        if(recipientTrainer != null){
            Component.Apex.OutputText ot = new Component.Apex.OutputText();
            ot.value='' + recipientTrainer[0].Bio__c;
               return ot; 
        }else{
        	return null;
        }
    }
    
    PageReference pageRef = ApexPages.currentPage();
    
    //Methods
    
    public void showMe() {
        system.debug(currTrade);
        
        system.debug(recipientTrainer);
    }
    
    public void saveOfferChanges() {
        List<Offer__C> updatedOffers = new List<Offer__c>();
        for (Offer__c o : offers) {
            if (o.Accepted__c == 'Pending') {
                o.Accepted__c = 'Declined';
            }
            updatedOffers.add(o);
        }
        update updatedOffers;
    }
}