PokeTradR/force-app/main/default/objects/Complaint__c/Complaint__c.object-meta.xml
<CustomObject>
    <description>Complaints made toward another Trainer</description>
    <label>Complaint</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Complaint Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/objects/Complaint__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <description>Extra information for Trainer to write here</description>
    <inlineHelpText>Please enter more detail for us to look into the matter</inlineHelpText>
    <label>Issue</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Complaint__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Reasoning for the complaint</description>
    <label>Reason</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Harassment</fullName>
            </value>
            <value>
                <fullName>Scamming</fullName>
            </value>
            <value>
                <fullName>Inappropriate Behavior</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PokeTradR/force-app/main/default/objects/Complaint__c/fields/Trainer_Being_Reported__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Being_Reported__c</fullName>
    <label>Trainer Being Reported</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Complaint__c/fields/Trainer_Reported__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Reported__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who&apos;s being reported?</description>
    <label>Trainer Reported</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Complaints (Trainer Reported)</relationshipLabel>
    <relationshipName>Complaints1</relationshipName>
    <type>Lookup</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <description>Account of Trainers</description>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/classes/TrainerSearchExtensionTest.cls
@isTest
public class TrainerSearchExtensionTest {
	
   @testSetup
    public static void newTR(){
     //create a trainer being reported, query it, and use the id as the relationship field.
     Trainer__c newT = new Trainer__c(
     		Name = 'Testy Dummy'
     );
        
      insert newT;  
     
     Trainer__c newTrainer = [SELECT Id, Name FROM Trainer__c WHERE Name=:'Testy Dummy'];
        
    Complaint__c newTrainerComplaint = new Complaint__c(
        Trainer_Being_Reported__c = 'Testy Dummy',
        Trainer_Reported__c = newTrainer.Id,
    	Reason__c = 'Harassment',
    	Issue__c = 'shshshs'
		);
        insert newTrainerComplaint;
        
    }
    
    
    @isTest
    public static void searchTest(){
 
        Test.startTest();
        PageReference pageRef = Page.TrainerComplaints;
        Test.setCurrentPage(pageRef);
        
        TrainerSearchExtension TSE = new TrainerSearchExtension(new apexPages.standardController([SELECT Trainer_Being_Reported__c FROM Complaint__c]));
		TSE.userInput = 'Testy Dummy';
        TSE.isSearched = true;
        TSE.returnMatchingComplaints();
        list<Complaint__c> newComplaint = TSE.searchComplaints;
        String name = newComplaint[0].Trainer_Being_Reported__c;
        Test.stopTest();
        
        system.assertEquals('Testy Dummy', name);
    }
    

}