PokeTradR/force-app/main/default/objects/Complaint__c/Complaint__c.object-meta.xml
<CustomObject>
    <description>Complaints made toward another Trainer</description>
    <label>Complaint</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Complaint Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/objects/Complaint__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <description>Extra information for Trainer to write here</description>
    <inlineHelpText>Please enter more detail for us to look into the matter</inlineHelpText>
    <label>Issue</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Complaint__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Reasoning for the complaint</description>
    <label>Reason</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Harassment</fullName>
            </value>
            <value>
                <fullName>Scamming</fullName>
            </value>
            <value>
                <fullName>Inappropriate Behavior</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PokeTradR/force-app/main/default/objects/Complaint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PokeTradR/force-app/main/default/objects/Complaint__c/fields/Trainer_Being_Reported__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Being_Reported__c</fullName>
    <label>Trainer Being Reported</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Complaint__c/fields/Trainer_Reported__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Reported__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who&apos;s being reported?</description>
    <label>Trainer Reported</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Complaints (Trainer Reported)</relationshipLabel>
    <relationshipName>Complaints1</relationshipName>
    <type>Lookup</type>
</CustomField>

PokeTradR/force-app/main/default/classes/TrainerSearchExtension.cls
public with sharing class TrainerSearchExtension{
    
    public String userInput {get;set;}
    public list<Complaint__c> searchComplaints {get; set;}
    public String errorMessage {get; set;}
    public String trainerName {get; set;}
    public boolean isSearched {get; set;}
    public list<Complaint__c> allTrainerComplaints = [SELECT Trainer_Being_Reported__c FROM Complaint__c];
    
   	public TrainerSearchExtension(ApexPages.StandardController sc){
       sc.getRecord();
   }
    
    public void returnMatchingComplaints(){
        try{
            isSearched = false;
            List<Complaint__c> complaintquery = new List<Complaint__c>();
            for(Complaint__c tc : allTrainerComplaints){
            if(this.userInput != '' || this.userInput != ' '){
                if(this.userInput == tc.Trainer_Being_Reported__c){
                   trainerName = String.escapeSingleQuotes(this.userInput);
                    isSearched = true;
                    complaintquery = Database.query('SELECT Trainer_Being_Reported__c, Trainer_Reported__c, Status__c, Reason__c, Issue__c FROM Complaint__c WHERE Trainer_Being_Reported__c =\''+
                                               this.trainerName+'\'');
            }
                    }
            }
                if(isSearched == true){
            		this.searchComplaints = complaintquery;
            	}
        }
        catch(exception e){
            this.errorMessage = 'Please enter a trainer\'s name in the search box.';
            this.searchComplaints = new list<Complaint__c>();
            
            }
        }
    }