PokeTradR/force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <description>Account of Trainers</description>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Birthday__c.field-meta.xml
<CustomField>
    <fullName>Birthday__c</fullName>
    <label>Birthday</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Dated_Joined__c.field-meta.xml
<CustomField>
    <fullName>Dated_Joined__c</fullName>
    <description>When they first joined PokeTradR</description>
    <label>Dated Joined</label>
    <type>Date</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Active - Profile can make trades and offers
Inactive - Profile can&apos;t make trades and offers
Frozen - Profile temporarily cannot make trades</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PokeTradR/force-app/main/default/classes/RegisterExtension.cls
public class RegisterExtension {
    private Trainer__c mytrainer;
	public RegisterExtension(ApexPages.StandardController sc){
        this.mytrainer = (Trainer__c)sc.getRecord();
	}
    //fill in extra info the the record and insert it to the database
    public Pagereference fillInAdditionalInfo(){
        //fill in and insert
        mytrainer.Age__c = (System.Today().Year() - mytrainer.Birthday__c.Year());
        mytrainer.Dated_Joined__c = System.Today();
        mytrainer.Status__c = 'Active';
        insert mytrainer;
        return Page.RegisterConfirmation;
    }
}