PokeTradR/force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <description>Account of Trainers</description>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Offers_Made__c.field-meta.xml
<CustomField>
    <fullName>Offers_Made__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offers Made</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <description>Based on total of Trades Made and Offers Made it will cause the Trainer Rank to assign: 
Rookie (&lt;25), 
Intermediate(&gt;= 25 &amp; &lt;50),
Advanced (&gt;= 50 &amp; &lt;75)
Master(&gt;= 75 &amp; &lt;100)</description>
    <label>Rank</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Trades_Made__c.field-meta.xml
<CustomField>
    <fullName>Trades_Made__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Trades Made</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PokeTradR/force-app/main/default/classes/TrainerRankUpdate.cls
public class TrainerRankUpdate {
    
    //Passing Trainer object as a list for the parameter
    public static void checkRank(List<Trainer__c> tList){
        
        //Empty trainer list to add to
        List<Trainer__c> updateList = new List<Trainer__c>();
        //As long as Trainer object equals the tList
        for(Trainer__c t: tList){
            //If the sum of Offers Made and Trades Made hit a certain threshold they rank up
            Double sum = t.Offers_Made__c + t.Trades_Made__c;
            if(sum < 25){
                t.Rank__c = 'Rookie';
            }
            else if(sum >= 25 && sum < 50){
                t.Rank__c = 'Intermediate';
            }
            else if(sum >= 50 && sum < 75){
                t.Rank__c = 'Expert';
            }
            else if(sum > 75){
                t.Rank__c = 'Master';
            }
                
        }
    }

}