PokeTradR/force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <description>Account of Trainers</description>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Birthday__c.field-meta.xml
<CustomField>
    <fullName>Birthday__c</fullName>
    <label>Birthday</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Dated_Joined__c.field-meta.xml
<CustomField>
    <fullName>Dated_Joined__c</fullName>
    <description>When they first joined PokeTradR</description>
    <label>Dated Joined</label>
    <type>Date</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Active - Profile can make trades and offers
Inactive - Profile can&apos;t make trades and offers
Frozen - Profile temporarily cannot make trades</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PokeTradR/force-app/main/default/classes/RegisterExTest.cls
@isTest
public class RegisterExTest {
	@isTest
    public static void resTest(){
        Test.startTest();
        //set the current page
        PageReference thispage = Page.TrainerProfile;
        Test.setCurrentPage(thispage);
        
        Trainer__c t = new Trainer__c(Name ='Test', Password__c ='123456', First_Name__c = 'A', Last_Name__c = 'B',Birthday__c =Date.newInstance(1991, 12, 21));
        ApexPages.StandardController sc = new ApexPages.StandardController(t);
        RegisterExtension temp = new RegisterExtension(sc);
        temp.fillInAdditionalInfo();
        Trainer__c myt = [SELECT Age__c, Dated_Joined__c, Status__c FROM Trainer__c WHERE Name = 'Test' LIMIT 1];
        test.stopTest();
       	System.debug(myt);
        System.assertNotEquals(null, myt.Age__c);
        System.assertEquals(System.today(), myt.Dated_Joined__c);
        System.assertEquals('Active', myt.Status__c);
    }
    @isTest
    public static void trans(){
        Test.startTest();
        //set the current page
        PageReference thispage = Page.RegisterConfirmation;
        Test.setCurrentPage(thispage);
               
        RegisterBackToLogin temp = new RegisterBackToLogin();
        PageReference page = temp.backToLogin();
        test.stopTest();
       
        System.assertNotEquals(thispage, page);
    }
}