PokeTradR/force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <description>Account of Trainers</description>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Current_Offers__c.field-meta.xml
<CustomField>
    <fullName>Current_Offers__c</fullName>
    <label>Current Offers</label>
    <summarizedField>Offer__c.Number__c</summarizedField>
    <summaryForeignKey>Offer__c.Trainer_Name__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Trainer__c/fields/Offers_Made__c.field-meta.xml
<CustomField>
    <fullName>Offers_Made__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Offers Made</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PokeTradR/force-app/main/default/classes/TrainerOfferUpdate.cls
public class TrainerOfferUpdate {
    
    //Passing two different lists of the trainer object as 2 parameters
    public static void addOneOffer(List<Trainer__c> newList, List<Trainer__c> oldList){
        //system.debug(newList);
        //system.debug(oldList);
        //Declaring an empty list called updateList
        List<Trainer__c> updateList = new List<Trainer__c>();
        //Creating a nested for loop to check both new list and old list
        for(Trainer__c tn: newList){
            for(Trainer__c to: oldList){
                //If new Current Offers s greater than old Current Offers, increment Offers Made
                if(tn.Current_Offers__c > to.Current_Offers__c){
                    tn.Offers_Made__c++;
                    updateList.add(tn);
                    //extra
               }
            } 
        }
                
    }

}