PokeTradR/force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokedex Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemon</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/objects/Pokemon__c/fields/Attack__c.field-meta.xml
<CustomField>
    <fullName>Attack__c</fullName>
    <label>Attack</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Pokemon__c/fields/Defense__c.field-meta.xml
<CustomField>
    <fullName>Defense__c</fullName>
    <label>Defense</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Pokemon__c/fields/Entry__c.field-meta.xml
<CustomField>
    <fullName>Entry__c</fullName>
    <description>The Pokedex Entry of the Pokémon</description>
    <label>Entry</label>
    <type>TextArea</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Pokemon__c/fields/Height_m__c.field-meta.xml
<CustomField>
    <fullName>Height_m__c</fullName>
    <label>Height (m)</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Pokemon__c/fields/HP__c.field-meta.xml
<CustomField>
    <fullName>HP__c</fullName>
    <label>HP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Pokemon__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <label>Pokemon</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pokemon</valueSetName>
    </valueSet>
</CustomField>

PokeTradR/force-app/main/default/objects/Pokemon__c/fields/Special_Attack__c.field-meta.xml
<CustomField>
    <fullName>Special_Attack__c</fullName>
    <label>Special Attack</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Pokemon__c/fields/Special_Defense__c.field-meta.xml
<CustomField>
    <fullName>Special_Defense__c</fullName>
    <label>Special Defense</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Pokemon__c/fields/Speed__c.field-meta.xml
<CustomField>
    <fullName>Speed__c</fullName>
    <label>Speed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PokeTradR/force-app/main/default/objects/Pokemon__c/fields/Type1__c.field-meta.xml
<CustomField>
    <fullName>Type1__c</fullName>
    <description>Primary type for Pokemon</description>
    <label>Type1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type1</valueSetName>
    </valueSet>
</CustomField>

PokeTradR/force-app/main/default/objects/Pokemon__c/fields/Type2__c.field-meta.xml
<CustomField>
    <fullName>Type2__c</fullName>
    <description>Secondary Typing (if applicable)</description>
    <label>Type2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type2</valueSetName>
    </valueSet>
</CustomField>

PokeTradR/force-app/main/default/objects/Pokemon__c/fields/Weight_g__c.field-meta.xml
<CustomField>
    <fullName>Weight_g__c</fullName>
    <description>The Pokémon&apos;s weight</description>
    <label>Weight (g)</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

PokeTradR/force-app/main/default/globalValueSets/Pokemon.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abra</fullName>
    </customValue>
    <customValue>
        <fullName>Aerodactyl</fullName>
    </customValue>
    <customValue>
        <fullName>Alakazam</fullName>
    </customValue>
    <customValue>
        <fullName>Arbok</fullName>
    </customValue>
    <customValue>
        <fullName>Arcanine</fullName>
    </customValue>
    <customValue>
        <fullName>Articuno</fullName>
    </customValue>
    <customValue>
        <fullName>Beedrill</fullName>
    </customValue>
    <customValue>
        <fullName>Bellsprout</fullName>
    </customValue>
    <customValue>
        <fullName>Blastoise</fullName>
    </customValue>
    <customValue>
        <fullName>Bulbasaur</fullName>
    </customValue>
    <customValue>
        <fullName>Butterfree</fullName>
    </customValue>
    <customValue>
        <fullName>Caterpie</fullName>
    </customValue>
    <customValue>
        <fullName>Chansey</fullName>
    </customValue>
    <customValue>
        <fullName>Charizard</fullName>
    </customValue>
    <customValue>
        <fullName>Charmander</fullName>
    </customValue>
    <customValue>
        <fullName>Charmeleon</fullName>
    </customValue>
    <customValue>
        <fullName>Clefable</fullName>
    </customValue>
    <customValue>
        <fullName>Clefairy</fullName>
    </customValue>
    <customValue>
        <fullName>Cloyster</fullName>
    </customValue>
    <customValue>
        <fullName>Cubone</fullName>
    </customValue>
    <customValue>
        <fullName>Dewgong</fullName>
    </customValue>
    <customValue>
        <fullName>Diglett</fullName>
    </customValue>
    <customValue>
        <fullName>Ditto</fullName>
    </customValue>
    <customValue>
        <fullName>Dodrio</fullName>
    </customValue>
    <customValue>
        <fullName>Doduo</fullName>
    </customValue>
    <customValue>
        <fullName>Dragonair</fullName>
    </customValue>
    <customValue>
        <fullName>Dragonite</fullName>
    </customValue>
    <customValue>
        <fullName>Dratini</fullName>
    </customValue>
    <customValue>
        <fullName>Drowzee</fullName>
    </customValue>
    <customValue>
        <fullName>Dugtrio</fullName>
    </customValue>
    <masterLabel>Pokemon</masterLabel>
</GlobalValueSet>

PokeTradR/force-app/main/default/globalValueSets/Type1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bug</fullName>
    </customValue>
    <customValue>
        <fullName>Dark</fullName>
    </customValue>
    <customValue>
        <fullName>Dragon</fullName>
    </customValue>
    <customValue>
        <fullName>Electric</fullName>
    </customValue>
    <customValue>
        <fullName>Fairy</fullName>
    </customValue>
    <customValue>
        <fullName>Fighting</fullName>
    </customValue>
    <customValue>
        <fullName>Fire</fullName>
    </customValue>
    <customValue>
        <fullName>Flying</fullName>
    </customValue>
    <customValue>
        <fullName>Ghost</fullName>
    </customValue>
    <customValue>
        <fullName>Grass</fullName>
    </customValue>
    <customValue>
        <fullName>Ground</fullName>
    </customValue>
    <customValue>
        <fullName>Ice</fullName>
    </customValue>
    <customValue>
        <fullName>Normal</fullName>
    </customValue>
    <customValue>
        <fullName>Poison</fullName>
    </customValue>
    <customValue>
        <fullName>Psychic</fullName>
    </customValue>
    <customValue>
        <fullName>Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Steel</fullName>
    </customValue>
    <customValue>
        <fullName>Water</fullName>
    </customValue>
    <masterLabel>Type1</masterLabel>
</GlobalValueSet>

PokeTradR/force-app/main/default/globalValueSets/Type2.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bug</fullName>
    </customValue>
    <customValue>
        <fullName>Dark</fullName>
    </customValue>
    <customValue>
        <fullName>Dragon</fullName>
    </customValue>
    <customValue>
        <fullName>Electric</fullName>
    </customValue>
    <customValue>
        <fullName>Fairy</fullName>
    </customValue>
    <customValue>
        <fullName>Fighting</fullName>
    </customValue>
    <customValue>
        <fullName>Fire</fullName>
    </customValue>
    <customValue>
        <fullName>Flying</fullName>
    </customValue>
    <customValue>
        <fullName>Ghost</fullName>
    </customValue>
    <customValue>
        <fullName>Grass</fullName>
    </customValue>
    <customValue>
        <fullName>Ground</fullName>
    </customValue>
    <customValue>
        <fullName>Ice</fullName>
    </customValue>
    <customValue>
        <fullName>Normal</fullName>
    </customValue>
    <customValue>
        <fullName>Poison</fullName>
    </customValue>
    <customValue>
        <fullName>Psychic</fullName>
    </customValue>
    <customValue>
        <fullName>Rock</fullName>
    </customValue>
    <customValue>
        <fullName>Steel</fullName>
    </customValue>
    <customValue>
        <fullName>Water</fullName>
    </customValue>
    <masterLabel>Type2</masterLabel>
</GlobalValueSet>

PokeTradR/force-app/main/default/classes/PokemonSearchController.cls
public class PokemonSearchController {
    
    //Setting up our variables for our method
    public String pokemonName{get;set;}
    public Boolean renderTable{get;set;}
    public ApexPages.StandardSetController setController {get;set;}
    public String testName = 'Test';
    //public static List<Pokemon__c> poke; 
    
    //Where our queried result will be stored
    public List<Pokemon__c> pokemon {get{
        return this.setController.getSelected();
    }}
    
    //Initially setting up the table as false when nothing is searched
    Public PokemonSearchController(){    
        this.renderTable=false;
    }
    
    //User will input a pokemon name and it will return the pokedex entry on that particular one
    public void searchForPokemon(){
        
        //Using string.escapeSingleQuotes to protect data in the org from malicious attempts
        this.pokemonName = String.escapeSingleQuotes(this.pokemonName);
        List<Pokemon__c> poke = Database.query('SELECT Id, Pokemon__c, Height_m__c, Weight_g__c, Type1__c, Type2__c, HP__c, Attack__c, Defense__c, Special_Attack__c, Special_Defense__c, Speed__c, Entry__c FROM Pokemon__c WHERE Pokemon__c=\''+
                                               this.pokemonName+'\'');
        system.debug(poke);
        if(this.setController==null){
            this.setController = new ApexPages.StandardSetController(poke);
            system.debug(this.setController.getSelected());
        }else{
            this.setController.setSelected(poke);
            system.debug(this.setController.getSelected());
        }
        if(this.renderTable != true){
            this.renderTable = true;
        }     
    }
    
    //public static void debug(){
        //system.debug(poke);
    //}
}