PokeTradR/force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokedex Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemon</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

PokeTradR/force-app/main/default/objects/Pokemon__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <label>Pokemon</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pokemon</valueSetName>
    </valueSet>
</CustomField>

PokeTradR/force-app/main/default/objects/Pokemon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PokeTradR/force-app/main/default/globalValueSets/Pokemon.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abra</fullName>
    </customValue>
    <customValue>
        <fullName>Aerodactyl</fullName>
    </customValue>
    <customValue>
        <fullName>Alakazam</fullName>
    </customValue>
    <customValue>
        <fullName>Arbok</fullName>
    </customValue>
    <customValue>
        <fullName>Arcanine</fullName>
    </customValue>
    <customValue>
        <fullName>Articuno</fullName>
    </customValue>
    <customValue>
        <fullName>Beedrill</fullName>
    </customValue>
    <customValue>
        <fullName>Bellsprout</fullName>
    </customValue>
    <customValue>
        <fullName>Blastoise</fullName>
    </customValue>
    <customValue>
        <fullName>Bulbasaur</fullName>
    </customValue>
    <customValue>
        <fullName>Butterfree</fullName>
    </customValue>
    <customValue>
        <fullName>Caterpie</fullName>
    </customValue>
    <customValue>
        <fullName>Chansey</fullName>
    </customValue>
    <customValue>
        <fullName>Charizard</fullName>
    </customValue>
    <customValue>
        <fullName>Charmander</fullName>
    </customValue>
    <customValue>
        <fullName>Charmeleon</fullName>
    </customValue>
    <customValue>
        <fullName>Clefable</fullName>
    </customValue>
    <customValue>
        <fullName>Clefairy</fullName>
    </customValue>
    <customValue>
        <fullName>Cloyster</fullName>
    </customValue>
    <customValue>
        <fullName>Cubone</fullName>
    </customValue>
    <customValue>
        <fullName>Dewgong</fullName>
    </customValue>
    <customValue>
        <fullName>Diglett</fullName>
    </customValue>
    <customValue>
        <fullName>Ditto</fullName>
    </customValue>
    <customValue>
        <fullName>Dodrio</fullName>
    </customValue>
    <customValue>
        <fullName>Doduo</fullName>
    </customValue>
    <customValue>
        <fullName>Dragonair</fullName>
    </customValue>
    <customValue>
        <fullName>Dragonite</fullName>
    </customValue>
    <customValue>
        <fullName>Dratini</fullName>
    </customValue>
    <customValue>
        <fullName>Drowzee</fullName>
    </customValue>
    <customValue>
        <fullName>Dugtrio</fullName>
    </customValue>
    <masterLabel>Pokemon</masterLabel>
</GlobalValueSet>

PokeTradR/force-app/main/default/classes/PokemonClassTest.cls
@IsTest
public class PokemonClassTest {

    //Setting up a test entry to search
    @TestSetup
    public static void testCreate(){
        Pokemon__c p = new Pokemon__c(
            Name='01 Test',
            Pokemon__c='Bulbasaur',
            Status__c='Approved'       
        );
        
        insert p;
    }    
    
    //Testing for the search function
    @IsTest 
    public static void testSearch(){
        Test.startTest();
            //Setting up our page reference for the visualforce page
            PageReference pageRef = Page.PokemonPage;
            Test.setCurrentPage(pageRef);
            //Pokemon search works off the Pokemon__c field which contains a picklist. Using Bulbasaur as the test
            String nameSearch = 'Bulbasaur';    
            PokemonSearchController ps = new PokemonSearchController();
            //Assigning the user input search to bulbasaur 
            ps.pokemonName = nameSearch;
            ps.renderTable = true;
            //invoking the method from controller
            ps.searchForPokemon(); 
            ps.setController = null;
            Pokemon__c pokemonTest = [SELECT Id, Name, Status__c FROM Pokemon__c WHERE Name='01 Test' Limit 1];
        Test.stopTest();	
        system.debug(ps.myId);
        system.debug(pokemonTest.Id);
        //Testing that the pokemon search Id matches the pokemon Test Id
        System.assertEquals(ps.myId,pokemonTest.Id); 
        
	}
    
    @IsTest 
    //Replicating above test, refactoring for code coverage on renderTable False
    public static void testSearch2(){
        Test.startTest();
            PageReference pageRef = Page.PokemonPage;
            Test.setCurrentPage(pageRef);
            String nameSearch = 'Bulbasaur';    
            PokemonSearchController ps = new PokemonSearchController();
            ps.pokemonName = nameSearch;
            ps.renderTable = false;
            ps.searchForPokemon(); 
            ps.setController = null;
            Pokemon__c pokemonTest = [SELECT Id, Name, Status__c FROM Pokemon__c WHERE Name='01 Test' Limit 1];
        Test.stopTest();	
        system.debug(ps.myId);
        system.debug(pokemonTest.Id);
        System.assertEquals(ps.myId,pokemonTest.Id); 
        
	}
    
    @IsTest 
    //Refactoring for when a search that doesn't equal a Pokemon name 
    public static void badSearch(){
        Test.startTest();
            PageReference pageRef = Page.PokemonPage;
            Test.setCurrentPage(pageRef);
            String nameSearch = '29398';    
            PokemonSearchController ps = new PokemonSearchController();
            ps.pokemonName = nameSearch;
            ps.renderTable = false;
            ps.searchForPokemon(); 
            ps.setController = null;
        Test.stopTest();	
        System.assertEquals(Null,ps.setController);     
	}
}